---
- name: This sets up an httpd webserver
  hosts: localhost
  tasks:
  
  - name: ping
    ping:

  - name: Install apache packages
    yum:
      name: httpd
      state: present
    tags: install
  - name: ensure httpd is running
    service:
      name: httpd
      state: started
