---
- name: This sets up an httpd webserver
  hosts: localhost
  tasks:
  
  - name: ping
    ping:
    tags: ping 
  
  - name: Print message
    debug:
      msg: Hello Ansible World
    tags: msg  
